# Generated by Django 4.1.4 on 2023-02-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('provider', models.CharField(max_length=150)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('quantity', models.IntegerField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='booking_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('total', models.IntegerField()),
                ('booking_status', models.BooleanField(default=False, help_text='0=Default, 1=Booked')),
                ('overdue_status', models.BooleanField(default=False, help_text='0=Default, 1 = Overdue')),
                ('overdue_time', models.BooleanField(default=False, help_text='0=Default, 1 = Overtime')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('security_deposit', models.DecimalField(decimal_places=10, max_digits=20)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('payment_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.payment_detail')),
            ],
        ),
    ]
