# Generated by Django 4.1.4 on 2023-02-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=False, help_text='0=Default, 1=Hidden'),
        ),
        migrations.AddField(
            model_name='book',
            name='trending',
            field=models.BooleanField(default=False, help_text='0=Default, 1=Trending'),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False, help_text='0=Default, 1=Hidden'),
        ),
        migrations.AddField(
            model_name='category',
            name='trending',
            field=models.BooleanField(default=False, help_text='0=Default, 1=Trending'),
        ),
    ]
