# Generated by Django 4.1.4 on 2023-02-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_user_alter_book_inventory_book_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='middle_name',
            new_name='middlename',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
