# Generated by Django 4.1.4 on 2023-02-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_user_middlename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Book_id',
            new_name='book_id',
        ),
    ]
