# Generated by Django 4.1.6 on 2023-02-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_rename_book_id_cart_book_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking_item',
        ),
    ]
