# Generated by Django 4.1.4 on 2023-03-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalitem',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
