# Generated by Django 4.1.4 on 2023-03-09 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_finalitem_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalitem',
            name='deadline_date',
            field=models.DateField(default=datetime.date(2023, 4, 8)),
        ),
        migrations.AddField(
            model_name='finalitem',
            name='remaining_days',
            field=models.IntegerField(default=0),
        ),
    ]
