# Generated by Django 4.1.4 on 2023-03-09 16:59

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_finalitem_deadline_date_finalitem_remaining_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalitem',
            name='image_data',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path),
        ),
    ]
