# Generated by Django 4.1.4 on 2023-03-23 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_finalitem_deadline_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='finalitem',
            name='deadline_date',
            field=models.DateField(default=datetime.date(2023, 4, 22)),
        ),
        migrations.AlterField(
            model_name='finalitem',
            name='remaining_days',
            field=models.IntegerField(default=0),
        ),
    ]
